module.exports = {
  content: [
    "./index.html",
    "./about.html",
    "./activities.html",
    "./coaches.html",
    "./contact.html",
    "./events.html",
    "./gallery.html",
    "./locations.html",
    "./pricing.html",
    "./404.html"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#00173d",
        secondary: "#1e6583",
        accent: "#F4B400",
        background: "#faf8fe",
        surface: "#ffffff",
        "surface-dark": "#0b132b",
        "slate-neutral": "#475569",
        "surface-variant": "#e3e2e7",
        "surface-container-high": "#e9e7ed",
        "on-primary-container": "#7994d0",
        "surface-bright": "#faf8fe",
        "surface-container": "#eeedf2",
        "on-secondary-fixed": "#001e2c",
        "tertiary-fixed-dim": "#ffb693",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#004d67",
        "on-secondary-container": "#196280",
        "primary-fixed-dim": "#aec6ff",
        "inverse-primary": "#aec6ff",
        "outline": "#747781",
        "tertiary-fixed": "#ffdbcc",
        "on-tertiary-fixed-variant": "#723615",
        "surface-dim": "#dad9df",
        "inverse-on-surface": "#f1f0f5",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#d0815a",
        "tertiary": "#300e00",
        "primary-fixed": "#d8e2ff",
        "secondary-fixed": "#c2e8ff",
        "on-background": "#1a1b1f",
        "surface-container-highest": "#e3e2e7",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#90cff1",
        "on-tertiary-fixed": "#351000",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001a43",
        "on-surface": "#1a1b1f",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-tint": "#425d96",
        "outline-variant": "#c4c6d1",
        "primary-container": "#072b61",
        "on-surface-variant": "#444750",
        "inverse-surface": "#2f3034",
        "on-error": "#ffffff",
        "secondary-container": "#9fdcff",
        "on-primary-fixed-variant": "#29457c",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f8",
        "tertiary-container": "#511d00"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "md": "24px",
        "xs": "4px",
        "margin-desktop": "40px",
        "lg": "48px",
        "container-max": "1280px",
        "xl": "80px",
        "base": "8px",
        "sm": "12px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        display: ["Outfit", "sans-serif"],
        body: ["Inter", "sans-serif"],
        "headline-md": ["Outfit"],
        "headline-sm": ["Outfit"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Outfit"],
        "label-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Outfit"],
        "headline-lg": ["Outfit"]
      },
      fontSize: {
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-lg": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
